{% set name = "pyobjc-framework-webkit" %}
{% set version = "10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/pyobjc-framework-WebKit/pyobjc-framework-WebKit-{{ version }}.tar.gz
  sha256: 847a69aeeb2e743c5ff838628f3a0031e538de4e011e29df52272955ed0b11df

build:
  script:
    # force pyobjc to use conda-forge's chosen SDK
    - export CFLAGS="${CFLAGS} -isysroot ${SDKROOT:-$CONDA_BUILD_SYSROOT}"
    # force ignoring invalid compiler flag (-Wl,-export-dynamic)
    - export CFLAGS="${CFLAGS} -Wno-unused-command-line-argument"  # [py == 37 or py == 38]
    - {{ PYTHON }} -m pip install --no-deps . -vv
  skip: true  # [not osx or py2k or python_impl == 'pypy' or (arm64 and py < 39)]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - libffi
  run:
    - python
    - pyobjc-core {{ version }}
    - pyobjc-framework-cocoa {{ version }}
    - libffi

test:
  imports:
    - WebKit
    - JavaScriptCore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ronaldoussoren/pyobjc
  dev_url: https://github.com/ronaldoussoren/pyobjc/tree/master/pyobjc-framework-Webkit
  doc_url: https://pyobjc.readthedocs.io/en/latest/
  summary: Wrappers for the framework Webkit on macOS
  license: MIT
  license_file: License.txt

extra:
  recipe-maintainers:
    - traversaro
